export const places = [
    {
        place_id: 1,
        place_name: '東京タワー',
        lat: 35.6585805,
        lng: 139.7454329,
        place_description: '1958年に完成した高さ333mの総合電波塔です。長年東京のシンボルとして親しまれ、その赤と白の美しいフォルムはランドマークとして定着しています。メインデッキからは関東平野を一望でき、夜のライトアップも季節ごとに変化します。',
        place_photo_url: null as string | null,
        place_era_start: 1958 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 2,
        place_name: '東京スカイツリー',
        lat: 35.7100627,
        lng: 139.8107004,
        place_description: '2012年に開業した高さ634mを誇る世界一高い自立式電波塔です。天望デッキと天望回廊からは、晴天時には富士山まで見渡せる絶景が広がります。足元には商業施設「東京ソラマチ」があり、ショッピングや水族館も楽しめます。',
        place_photo_url: null as string | null,
        place_era_start: 2012 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 3,
        place_name: '浅草寺',
        lat: 35.7147651,
        lng: 139.7966553,
        place_description: '628年に創建されたと伝わる都内最古の寺院です。「雷門」の大提灯や、土産物店が立ち並ぶ「仲見世通り」は世界的にも有名です。江戸時代には徳川将軍家の祈願所として栄え、現在も年間を通して多くの参拝客で賑わいます。',
        place_photo_url: null as string | null,
        place_era_start: 628 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 4,
        place_name: '明治神宮',
        lat: 35.6763976,
        lng: 139.6993259,
        place_description: '明治天皇と昭憲皇太后をお祀りする神社です。1920年に創建され、広大な鎮守の杜は全国からの献木によって造成されました。都会の真ん中にありながら豊かな自然が広がり、初詣の参拝者数は日本一を誇ります。',
        place_photo_url: null as string | null,
        place_era_start: 1920 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 5,
        place_name: '皇居（旧江戸城）',
        lat: 35.685175,
        lng: 139.7527995,
        place_description: 'かつての江戸城跡に位置する天皇陛下の御所です。二重橋や伏見櫓などの歴史的建造物が残り、東御苑は一般公開されています。周囲のお濠や石垣は、徳川幕府の権威と当時の築城技術の高さを今に伝えています。',
        place_photo_url: null as string | null,
        place_era_start: 1457 as number | null, // 太田道灌による築城開始
        place_era_end: null as number | null,
    },
    {
        place_id: 6,
        place_name: '東京駅（丸の内駅舎）',
        lat: 35.6812362,
        lng: 139.7671248,
        place_description: '1914年に開業した日本の鉄道網の起点となるターミナル駅です。辰野金吾設計による赤レンガ造りの駅舎は、国の重要文化財に指定されています。2012年に復原工事が完了し、創建当時の美しいドーム屋根が蘇りました。',
        place_photo_url: null as string | null,
        place_era_start: 1914 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 7,
        place_name: '上野恩賜公園',
        lat: 35.7140708,
        lng: 139.7741094,
        place_description: '1873年に指定された日本最初の公園の一つです。園内には博物館、美術館、動物園、芸術大学などが集積しており、文化・芸術の拠点となっています。春には桜の名所として、多くの花見客で賑わいを見せます。',
        place_photo_url: null as string | null,
        place_era_start: 1873 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 8,
        place_name: '新宿御苑',
        lat: 35.6851774,
        lng: 139.7100516,
        place_description: '江戸時代の信州高遠藩主内藤家の下屋敷跡に造られた国民公園です。フランス式整形庭園、イギリス風景式庭園、日本庭園が巧みに組み合わされています。春の桜、秋の紅葉など、四季折々の自然を楽しむことができます。',
        place_photo_url: null as string | null,
        place_era_start: 1906 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 9,
        place_name: '渋谷スクランブル交差点',
        lat: 35.659482,
        lng: 139.700553,
        place_description: '世界で最も有名な交差点の一つと言われ、一度の青信号で最大3000人が横断するとも言われます。巨大な広告ビジョンと人波が織りなす風景は、現代の東京のエネルギーを象徴するスポットとして海外からも注目されています。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 10,
        place_name: '築地場外市場',
        lat: 35.6654865,
        lng: 139.7706668,
        place_description: 'かつての中央卸売市場に隣接して発展した商店街です。市場移転後も「食のまち」としての活気は健在で、新鮮な海産物、乾物、調理道具などを扱う専門店が密集しています。食べ歩きや寿司の名店を目当てに多くの人が訪れます。',
        place_photo_url: null as string | null,
        place_era_start: 1935 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 11,
        place_name: '東京国立博物館',
        lat: 35.7187848,
        lng: 139.7764831,
        place_description: '1872年に創設された日本最古の博物館です。日本および東洋の美術・考古など多岐にわたる文化財を収蔵・展示しています。本館、表慶館、東洋館など、建物自体も歴史的価値が高く、重要文化財に指定されているものもあります。',
        place_photo_url: null as string | null,
        place_era_start: 1872 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 12,
        place_name: '三鷹の森ジブリ美術館',
        lat: 35.696238,
        lng: 139.5704317,
        place_description: 'スタジオジブリ作品の世界観を体験できる美術館です。宮崎駿監督がデザインを手がけ、「迷子になろうよ、いっしょに。」をコンセプトにしています。館内では短編映画の上映や、制作資料の展示が行われています。',
        place_photo_url: null as string | null,
        place_era_start: 2001 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 13,
        place_name: '国立新美術館',
        lat: 35.6652631,
        lng: 139.7263725,
        place_description: '黒川紀章設計による波打つようなガラスのカーテンウォールが印象的な美術館です。コレクションを持たず、国内最大級の展示スペースを生かして多彩な企画展や公募展を開催しています。六本木のアートトライアングルの一角です。',
        place_photo_url: null as string | null,
        place_era_start: 2007 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 14,
        place_name: '江戸東京博物館',
        lat: 35.6963842,
        lng: 139.7964321,
        place_description: '江戸から現代の東京に至る歴史と文化を展示する博物館です。実物大で復元された日本橋や中村座、当時の町並みの模型などを通じて、庶民の生活や都市の変遷を体感的に学ぶことができます。（※大規模改修中の場合あり）',
        place_photo_url: null as string | null,
        place_era_start: 1993 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 15,
        place_name: '国立科学博物館',
        lat: 35.716335,
        lng: 139.7763878,
        place_description: '1877年に設立された日本唯一の国立総合科学博物館です。「日本館」と「地球館」があり、忠犬ハチ公の剥製から恐竜の骨格標本、最新の科学技術まで、自然史と科学技術史に関する膨大な資料を展示しています。',
        place_photo_url: null as string | null,
        place_era_start: 1877 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 16,
        place_name: '根津美術館',
        lat: 35.662243,
        lng: 139.718873,
        place_description: '実業家・初代根津嘉一郎の古美術コレクションを展示するために設立されました。隈研吾設計の和風モダンな本館と、都心とは思えない静寂に包まれた広大な日本庭園が調和しており、国宝「燕子花図屏風」の所蔵で知られます。',
        place_photo_url: null as string | null,
        place_era_start: 1941 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 17,
        place_name: '森ビル デジタルアート ミュージアム',
        lat: 35.6599708,
        lng: 139.743141,
        place_description: 'アート集団チームラボによる「地図のないミュージアム」です。境界のないアート作品群が部屋から出て移動し、他の作品と影響し合いながら融合します。身体ごと没入できる新しい形のアート体験を提供しています。',
        place_photo_url: null as string | null,
        place_era_start: 2018 as number | null, // お台場開業年、現在は麻布台ヒルズへ移転
        place_era_end: null as number | null,
    },
    {
        place_id: 18,
        place_name: '迎賓館赤坂離宮',
        lat: 35.6803273,
        lng: 139.7291882,
        place_description: '日本唯一のネオ・バロック様式の西洋風宮殿建築です。明治時代に東宮御所として建設され、現在は世界各国の国王や大統領などをお迎えする外交の舞台となっています。国宝に指定されており、一般公開も行われています。',
        place_photo_url: null as string | null,
        place_era_start: 1909 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 19,
        place_name: '東京都庁舎',
        lat: 35.6896342,
        lng: 139.6921007,
        place_description: '丹下健三設計による新宿副都心のシンボルです。第一本庁舎にある南北の展望室は無料で開放されており、地上202mの高さから東京の街並みを一望できます。夜景スポットとしても人気があります。',
        place_photo_url: null as string | null,
        place_era_start: 1991 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 20,
        place_name: '歌舞伎座',
        lat: 35.669537,
        lng: 139.767784,
        place_description: '世界で唯一の歌舞伎専門劇場です。現在の建物は第五期で、伝統的な桃山様式の外観を残しつつ、背後に高層オフィスビルを併設した複合施設となっています。一幕見席もあり、気軽に伝統芸能に触れることができます。',
        place_photo_url: null as string | null,
        place_era_start: 1889 as number | null, // 初代開場
        place_era_end: null as number | null,
    },
    {
        place_id: 21,
        place_name: '神田明神',
        lat: 35.702028,
        lng: 139.7679307,
        place_description: '730年創建と伝わる、江戸総鎮守として崇敬される神社です。神田、日本橋、秋葉原、大手町などの氏神様であり、商売繁盛や縁結びのご利益で知られます。秋葉原に近いため、ITお守りなども授与されています。',
        place_photo_url: null as string | null,
        place_era_start: 730 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 22,
        place_name: '靖国神社',
        lat: 35.6942023,
        lng: 139.7436668,
        place_description: '明治維新以降の国事に殉じた人々の霊を祀る神社です。境内にあるソメイヨシノの標本木は、気象庁が東京の桜の開花宣言を行う基準木として知られています。遊就館では遺品や史資料を展示しています。',
        place_photo_url: null as string | null,
        place_era_start: 1869 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 23,
        place_name: '増上寺',
        lat: 35.657418,
        lng: 139.748227,
        place_description: '浄土宗の七大本山の一つで、徳川将軍家の菩提寺です。東京タワーのすぐ足元に位置し、朱塗りの三解脱門と近代的なタワーのコントラストが特徴的です。境内には徳川将軍家の墓所があります。',
        place_photo_url: null as string | null,
        place_era_start: 1393 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 24,
        place_name: '湯島天満宮',
        lat: 35.707833,
        lng: 139.768407,
        place_description: '学問の神様である菅原道真公を祀る神社で、通称「湯島天神」と呼ばれます。受験シーズンには多くの学生が合格祈願に訪れます。また、江戸時代から梅の名所としても知られ、春には梅まつりが開催されます。',
        place_photo_url: null as string | null,
        place_era_start: 458 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 25,
        place_name: '富岡八幡宮',
        lat: 35.671911,
        lng: 139.799659,
        place_description: '江戸最大の八幡宮であり、江戸勧進相撲発祥の地として知られます。境内には横綱力士碑などの相撲関連の石碑が多くあります。夏に行われる「深川八幡祭り」は江戸三大祭りの一つに数えられ、水掛け祭りとして有名です。',
        place_photo_url: null as string | null,
        place_era_start: 1627 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 26,
        place_name: '浜離宮恩賜庭園',
        lat: 35.659666,
        lng: 139.763413,
        place_description: '江戸時代の代表的な大名庭園です。海水を引き入れた「潮入の池」があり、潮の干満によって景色の変化を楽しめます。園内の茶屋では抹茶を楽しむことができ、周囲の高層ビル群と庭園の対比が東京らしい景観です。',
        place_photo_url: null as string | null,
        place_era_start: 1654 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 27,
        place_name: '小石川後楽園',
        lat: 35.705193,
        lng: 139.749007,
        place_description: '水戸徳川家の上屋敷内に造られた回遊式築山泉水庭園です。中国の儒教思想の影響を色濃く受けており、「円月橋」など中国の景勝地を模した景観が見られます。国の特別史跡および特別名勝に指定されています。',
        place_photo_url: null as string | null,
        place_era_start: 1629 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 28,
        place_name: '日枝神社',
        lat: 35.674591,
        lng: 139.740228,
        place_description: '永田町に鎮座し、江戸城の鎮守神として崇められてきました。「山王さん」の愛称で親しまれ、6月の山王祭は天下祭として有名です。社殿へ続く階段にはエスカレーターが設置されており、近代的な設備も特徴です。',
        place_photo_url: null as string | null,
        place_era_start: 1478 as number | null, // 文明10年に太田道灌が勧請
        place_era_end: null as number | null,
    },
    {
        place_id: 29,
        place_name: '豪徳寺',
        lat: 35.648347,
        lng: 139.646845,
        place_description: '世田谷区にある曹洞宗の寺院で、井伊家の菩提寺です。「招き猫発祥の地」の一つとされ、奉納された数千体の招き猫が並ぶ「招猫殿」は圧巻の光景です。海外からの観光客にも人気のフォトスポットとなっています。',
        place_photo_url: null as string | null,
        place_era_start: 1480 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 30,
        place_name: '日本橋',
        lat: 35.684058,
        lng: 139.774501,
        place_description: '五街道の起点として江戸の交通の中心であった橋です。現在の橋は1911年に完成した石造二連アーチ橋で、重要文化財です。橋の中央には「日本国道路元標」があり、日本の道路網の始点であることを示しています。',
        place_photo_url: null as string | null,
        place_era_start: 1603 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 31,
        place_name: '六本木ヒルズ',
        lat: 35.660464,
        lng: 139.729249,
        place_description: 'オフィス、住宅、ホテル、美術館、映画館などが集約された複合都市です。中心となる森タワーの展望台「東京シティビュー」からは、東京タワーを間近に見下ろす絶景が楽しめます。',
        place_photo_url: null as string | null,
        place_era_start: 2003 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 32,
        place_name: 'お台場海浜公園',
        lat: 35.629392,
        lng: 139.775358,
        place_description: '東京湾に面した人工の砂浜と公園です。レインボーブリッジや対岸の都心のビル群を一望でき、特に夕暮れから夜景の時間帯が美しいです。自由の女神像があり、デートスポットや家族連れの憩いの場として人気です。',
        place_photo_url: null as string | null,
        place_era_start: 1996 as number | null, // 一部開園はもっと前だがリニューアル等含む
        place_era_end: null as number | null,
    },
    {
        place_id: 33,
        place_name: '井の頭恩賜公園',
        lat: 35.699709,
        lng: 139.573215,
        place_description: '武蔵野の面影を残す緑豊かな公園です。中央の井の頭池ではボート遊びができ、春は桜が池の水面に映り込みます。動物園（自然文化園）が併設されており、吉祥寺の街とも隣接しているため、散策に最適です。',
        place_photo_url: null as string | null,
        place_era_start: 1917 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 34,
        place_name: '竹下通り',
        lat: 35.671449,
        lng: 139.704273,
        place_description: '原宿駅前から続く商店街で、日本の「カワイイ」カルチャーの発信地です。クレープ店や個性的なファッションショップが軒を連ね、常に若者や観光客で溢れています。最新の流行を肌で感じることができるスポットです。',
        place_photo_url: null as string | null,
        place_era_start: 1970 as number | null, // 歩行者天国開始頃から若者の街へ
        place_era_end: null as number | null,
    },
    {
        place_id: 35,
        place_name: 'アメ横商店街',
        lat: 35.708892,
        lng: 139.774439,
        place_description: '上野駅から御徒町駅の間の高架下に広がる商店街です。戦後の闇市を起源とし、現在も鮮魚、乾物、衣類、雑貨などを扱う店がひしめき合っています。年末の買い出し風景は東京の冬の風物詩となっています。',
        place_photo_url: null as string | null,
        place_era_start: 1946 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 36,
        place_name: '銀座四丁目交差点',
        lat: 35.671079,
        lng: 139.764906,
        place_description: '銀座の中心地であり、和光の時計塔と銀座三越が対角に位置する交差点です。高級ブランド店や老舗百貨店が立ち並び、日本一地価が高い場所としても知られます。週末は歩行者天国となり、銀ブラを楽しむ人々で賑わいます。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 37,
        place_name: '代々木公園',
        lat: 35.671649,
        lng: 139.695304,
        place_description: '都心で一番広い空が見える森林公園です。かつては陸軍の練兵場や米軍宿舎（ワシントンハイツ）、東京五輪の選手村でした。週末には様々な国際フェスティバルやイベントが開催され、多くの人で賑わいます。',
        place_photo_url: null as string | null,
        place_era_start: 1967 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 38,
        place_name: '等々力渓谷',
        lat: 35.606367,
        lng: 139.645732,
        place_description: '東京23区内唯一の渓谷です。多摩川に注ぐ谷沢川沿いに遊歩道が整備されており、都会の喧騒を忘れるような静寂と自然が残っています。古墳や不動の滝などの史跡もあり、夏は涼を求める人々で賑わいます。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 39,
        place_name: 'サンシャイン60',
        lat: 35.729503,
        lng: 139.718058,
        place_description: '池袋にある超高層ビルです。かつて東洋一の高さを誇りました。最上階の展望台「てんぼうパーク」に加え、水族館、プラネタリウム、ナンジャタウンなどのアミューズメント施設が充実しており、一日中楽しめます。',
        place_photo_url: null as string | null,
        place_era_start: 1978 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 40,
        place_name: '秋葉原電気街',
        lat: 35.699667,
        lng: 139.771343,
        place_description: '世界有数の電気街であり、アニメ、マンガ、ゲームなどのサブカルチャーの聖地です。電子部品から最新家電、メイドカフェまで多種多様な店舗が集まり、独特の熱気を放っています。外国人観光客にも大変人気があります。',
        place_photo_url: null as string | null,
        place_era_start: 1945 as number | null, // 闇市からの発展
        place_era_end: null as number | null,
    },
    {
        place_id: 41,
        place_name: '東京ドーム',
        lat: 35.705623,
        lng: 139.751919,
        place_description: '日本初の屋根付き球場です。読売ジャイアンツの本拠地であり、野球観戦だけでなく、大規模なコンサートやイベント会場としても使用されます。併設の「東京ドームシティ」には遊園地やスパ施設などがあります。',
        place_photo_url: null as string | null,
        place_era_start: 1988 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 42,
        place_name: '深大寺',
        lat: 35.666278,
        lng: 139.549219,
        place_description: '調布市にある、浅草寺に次いで都内で二番目に古い歴史を持つ古刹です。豊かな湧き水に恵まれ、周辺には名物の「深大寺そば」を食べさせる店が立ち並びます。隣接する神代植物公園とともに、自然と歴史を楽しめるスポットです。',
        place_photo_url: null as string | null,
        place_era_start: 733 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 43,
        place_name: '柴又帝釈天',
        lat: 35.758414,
        lng: 139.878342,
        place_description: '映画「男はつらいよ」の舞台として有名な葛飾区柴又にある寺院です。見事な木彫刻のギャラリーや庭園が見どころです。参道には草団子の店やレトロな建物が並び、下町の風情を色濃く残しています。',
        place_photo_url: null as string | null,
        place_era_start: 1629 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 44,
        place_name: '高尾山',
        lat: 35.625078,
        lng: 139.243685,
        place_description: '都心から電車で約1時間で行ける標高599mの山です。ミシュラン・グリーンガイドで三つ星を獲得しました。ケーブルカーやリフトもあり、初心者でも気軽に登山を楽しめるため、世界一登山客が多い山と言われています。',
        place_photo_url: null as string | null,
        place_era_start: 744 as number | null, // 薬王院開山
        place_era_end: null as number | null,
    },
    {
        place_id: 45,
        place_name: '谷中銀座商店街',
        lat: 35.727581,
        lng: 139.765662,
        place_description: '下町情緒が残る「谷根千」エリアを代表する商店街です。「夕やけだんだん」と呼ばれる階段からの夕景が有名で、惣菜店や猫グッズの店などが並びます。昭和レトロな雰囲気を求めて多くの人が散策に訪れます。',
        place_photo_url: null as string | null,
        place_era_start: 1945 as number | null, // 戦後自然発生的に形成
        place_era_end: null as number | null,
    },
    {
        place_id: 46,
        place_name: '豊洲市場',
        lat: 35.644463,
        lng: 139.785758,
        place_description: '2018年に築地から移転した公設卸売市場です。最新の衛生管理機能を備えた閉鎖型施設で、マグロの競りを見学デッキから見ることができます。新鮮な魚介類を楽しめる飲食店街や、屋上緑化広場も併設されています。',
        place_photo_url: null as string | null,
        place_era_start: 2018 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 47,
        place_name: '旧古河庭園',
        lat: 35.742468,
        lng: 139.746687,
        place_description: '大正初期の庭園の原型を留める国の名勝です。ジョサイア・コンドル設計の石造りの洋館と洋風庭園、そして小川治兵衛作庭の日本庭園が見事に調和しています。春と秋にはバラの名所として華やかに彩られます。',
        place_photo_url: null as string | null,
        place_era_start: 1919 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 48,
        place_name: '国立競技場',
        lat: 35.677918,
        lng: 139.714247,
        place_description: '2020年東京オリンピック・パラリンピックのメインスタジアムです。隈研吾氏らが設計し、「杜のスタジアム」をコンセプトに、木材を多用した和のテイストが特徴です。周辺の神宮外苑の緑と調和したデザインとなっています。',
        place_photo_url: null as string | null,
        place_era_start: 2019 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 49,
        place_name: '両国国技館',
        lat: 35.696956,
        lng: 139.793309,
        place_description: '大相撲の聖地であり、年3回の東京本場所が開催されます。すり鉢状の客席と吊り屋根が特徴的です。相撲博物館が併設されているほか、場所中以外でもイベント会場として使用されます。焼き鳥が名物です。',
        place_photo_url: null as string | null,
        place_era_start: 1985 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 50,
        place_name: 'レインボーブリッジ',
        lat: 35.636564,
        lng: 139.763143,
        place_description: '芝浦とお台場を結ぶ吊り橋で、東京港のシンボルです。遊歩道（レインボープロムナード）があり、歩いて渡ることも可能です。夜間は季節やイベントに合わせて美しくライトアップされ、東京湾の夜景を彩ります。',
        place_photo_url: null as string | null,
        place_era_start: 1993 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 51,
        place_name: '東京国際フォーラム',
        lat: 35.676398,
        lng: 139.763567,
        place_description: '旧都庁舎跡地に建設されたコンベンションセンターです。ラファエル・ヴィニオリ設計による巨大な船を模したガラス棟が特徴的で、建築写真の撮影スポットとしても非常に人気があります。',
        place_photo_url: null as string | null,
        place_era_start: 1997 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 52,
        place_name: '中銀カプセルタワービル',
        lat: 35.667683,
        lng: 139.761044,
        place_description: '黒川紀章設計によるメタボリズム建築の代表作です。着脱可能なカプセル型の住居が積み重なった特異な外観で世界的に有名でしたが、老朽化により惜しまれつつ解体されました。現在は一部が美術館等で保存されています。',
        place_photo_url: null as string | null,
        place_era_start: 1972 as number | null,
        place_era_end: 2022 as number | null,
    },
    {
        place_id: 53,
        place_name: '凌雲閣（浅草十二階）',
        lat: 35.715893,
        lng: 139.794468,
        place_description: '明治時代の浅草にそびえ立った12階建ての展望塔です。日本初のエレベーターを備え、当時の東京を見下ろす大人気スポットでしたが、関東大震災で半壊し、その後爆破解体されました。江戸川乱歩の作品などにも登場します。',
        place_photo_url: null as string | null,
        place_era_start: 1890 as number | null,
        place_era_end: 1923 as number | null,
    },
    {
        place_id: 54,
        place_name: '東急プラザ表参道「オモカド」（旧原宿セントラルアパート）',
        lat: 35.669145,
        lng: 139.705869,
        place_description: 'かつてこの地には、1960年代の若者文化やクリエイターの拠点となった「原宿セントラルアパート」がありました。現在は鏡張りの入り口が特徴的な商業施設となり、屋上の「おもはらの森」は憩いの場となっています。',
        place_photo_url: null as string | null,
        place_era_start: 2012 as number | null, // 現在の施設の開業
        place_era_end: null as number | null,
    },
    {
        place_id: 55,
        place_name: '鹿鳴館',
        lat: 35.673072,
        lng: 139.758656,
        place_description: '明治政府の欧化政策を象徴する西洋館です。ジョサイア・コンドルの設計で建設され、華やかな舞踏会が開かれましたが、老朽化により取り壊されました。現在はNBF日比谷ビルなどが建ち、記念碑が残るのみです。',
        place_photo_url: null as string | null,
        place_era_start: 1883 as number | null,
        place_era_end: 1940 as number | null,
    },
    {
        place_id: 56,
        place_name: '旧帝国ホテル（ライト館）',
        lat: 35.673231,
        lng: 139.759454,
        place_description: 'フランク・ロイド・ライトが設計した伝説的なホテルです。関東大震災にも耐えた堅牢さと、マヤ文明風の装飾が特徴でした。現在は玄関部分が愛知県の明治村に移築保存されていますが、元の場所には高層ホテルが建っています。',
        place_photo_url: null as string | null,
        place_era_start: 1923 as number | null,
        place_era_end: 1967 as number | null,
    },
    {
        place_id: 57,
        place_name: 'パレットタウン',
        lat: 35.624754,
        lng: 139.780650,
        place_description: 'お台場を代表する複合施設でした。大観覧車やヴィーナスフォート、Zepp Tokyoなどがありましたが、再開発計画に伴い営業を終了し解体されました。お台場のランドマークが大きく変化した出来事でした。',
        place_photo_url: null as string | null,
        place_era_start: 1999 as number | null,
        place_era_end: 2022 as number | null,
    },
    {
        place_id: 58,
        place_name: '同潤会青山アパートメント',
        lat: 35.667232,
        lng: 139.708873,
        place_description: '関東大震災後の復興支援で建設された集合住宅の一つです。ツタの絡まるレトロな外観が表参道の風景の一部として愛されていましたが、老朽化により建て替えられ、現在は「表参道ヒルズ」となっています。',
        place_photo_url: null as string | null,
        place_era_start: 1926 as number | null,
        place_era_end: 2003 as number | null,
    },
    {
        place_id: 59,
        place_name: 'としまえん',
        lat: 35.742353,
        lng: 139.646545,
        place_description: '練馬区にあった老舗遊園地です。世界最古級の回転木馬「カルーセルエルドラド」や流れるプールで親しまれましたが、閉園しました。跡地の一部は「ワーナー ブラザース スタジオツアー東京」として生まれ変わりました。',
        place_photo_url: null as string | null,
        place_era_start: 1926 as number | null,
        place_era_end: 2020 as number | null,
    },
    {
        place_id: 60,
        place_name: '国立西洋美術館',
        lat: 35.715387,
        lng: 139.775814,
        place_description: 'ル・コルビュジエが設計した本館は、世界文化遺産に登録されています。松方コレクションを中心とした西洋美術作品を展示しており、前庭にあるロダンの「考える人」や「地獄の門」の彫刻も有名です。',
        place_photo_url: null as string | null,
        place_era_start: 1959 as number | null,
        place_era_end: null as number | null,
    },

    // 61-70: 公園・庭園・自然
    {
        place_id: 61,
        place_name: '六義園',
        lat: 35.733075,
        lng: 139.746816,
        place_description: '柳沢吉保が造営した回遊式築山泉水庭園です。和歌の趣味を基調とした繊細な景観が特徴で、特に春のしだれ桜と秋の紅葉のライトアップは幻想的で多くの見物客が訪れます。国の特別名勝に指定されています。',
        place_photo_url: null as string | null,
        place_era_start: 1702 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 62,
        place_name: '清澄庭園',
        lat: 35.681146,
        lng: 139.797587,
        place_description: '明治の岩崎家が整備した回遊式林泉庭園です。全国から集められた名石が配置されており、「石の庭」とも呼ばれます。池の端を歩ける「磯渡り」が有名で、水面と松の緑、そして名石の調和が見事です。',
        place_photo_url: null as string | null,
        place_era_start: 1880 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 63,
        place_name: '旧岩崎邸庭園',
        lat: 35.710534,
        lng: 139.771146,
        place_description: '三菱財閥岩崎家の本邸でした。ジョサイア・コンドル設計の洋館と撞球室（ビリヤード場）、そして和館が併設されています。明治期の富豪の生活様式と建築美を今に伝える貴重な文化財です。',
        place_photo_url: null as string | null,
        place_era_start: 1896 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 64,
        place_name: '東京都庭園美術館（旧朝香宮邸）',
        lat: 35.636653,
        lng: 139.719639,
        place_description: 'アール・デコ様式の傑作として知られる旧朝香宮邸を利用した美術館です。建物そのものが芸術作品であり、内装のデザインや照明器具などが建設当時のまま保存されています。緑豊かな庭園も魅力です。',
        place_photo_url: null as string | null,
        place_era_start: 1933 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 65,
        place_name: '神代植物公園',
        lat: 35.670679,
        lng: 139.549219,
        place_description: '都内唯一の植物公園として開園しました。特にバラ園が有名で、春と秋には約400種類5200株のバラが咲き誇ります。大温室では熱帯植物やベゴニア、スイレンなどを一年中楽しむことができます。',
        place_photo_url: null as string | null,
        place_era_start: 1961 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 66,
        place_name: '葛西臨海公園',
        lat: 35.642738,
        lng: 139.862129,
        place_description: '東京湾に面した広大な公園です。ガラスドームが特徴的な「葛西臨海水族園」や、日本最大級のダイヤと花の大観覧車があります。人工渚では水遊びができ、野鳥の観察スポットとしても知られています。',
        place_photo_url: null as string | null,
        place_era_start: 1989 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 67,
        place_name: '国営昭和記念公園',
        lat: 35.707769,
        lng: 139.395759,
        place_description: '立川市と昭島市にまたがる広大な国営公園です。米軍立川基地跡地に造られました。春の桜、チューリップ、秋のコスモス、イチョウ並木など、四季折々の花々が大規模に植栽されており、ピクニックに最適です。',
        place_photo_url: null as string | null,
        place_era_start: 1983 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 68,
        place_name: '奥多摩湖（小河内ダム）',
        lat: 35.790518,
        lng: 139.050486,
        place_description: '多摩川を堰き止めて造られた東京都の貴重な水源地です。ダム湖百選にも選ばれており、春の桜や秋の紅葉が湖面に映える景色は絶景です。周辺には「ドラム缶橋」と呼ばれる浮き橋があり、歩いて渡ることができます。',
        place_photo_url: null as string | null,
        place_era_start: 1957 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 69,
        place_name: '日比谷公園',
        lat: 35.673646,
        lng: 139.756209,
        place_description: '日本初の西洋式近代公園です。ビジネス街のオアシスとして親しまれ、大音楽堂（野音）や公会堂などの文化施設があります。秋にはイチョウ並木が黄金色に輝き、クリスマスマーケットなどのイベントも盛んです。',
        place_photo_url: null as string | null,
        place_era_start: 1903 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 70,
        place_name: '飛鳥山公園',
        lat: 35.751351,
        lng: 139.737130,
        place_description: '徳川吉宗が桜を植えさせ、江戸庶民に開放したことで知られる古くからの桜の名所です。あじさいの名所でもあり、園内にはモノレール「アスカルゴ」が走っています。渋沢栄一の旧邸跡も隣接しています。',
        place_photo_url: null as string | null,
        place_era_start: 1720 as number | null, // 吉宗による桜の植樹と開放
        place_era_end: null as number | null,
    },
    {
        place_id: 71,
        place_name: '泉岳寺',
        lat: 35.637376,
        lng: 139.736952,
        place_description: '「忠臣蔵」で有名な赤穂浪士47士と主君・浅野内匠頭の墓所がある曹洞宗の寺院です。毎年12月14日の討ち入りの日には義士祭が開催され、多くの参拝者が訪れます。境内には義士記念館も併設されています。',
        place_photo_url: null as string | null,
        place_era_start: 1612 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 72,
        place_name: '根津神社',
        lat: 35.720339,
        lng: 139.760777,
        place_description: '江戸時代の権現造りの社殿が全て現存し、国の重要文化財に指定されています。境内にある「千本鳥居」がフォトジェニックなスポットとして人気です。春には「文京つつじまつり」が開催され、華やかに彩られます。',
        place_photo_url: null as string | null,
        place_era_start: 1705 as number | null, // 現在の社殿完成年
        place_era_end: null as number | null,
    },
    {
        place_id: 73,
        place_name: '亀戸天神社',
        lat: 35.703213,
        lng: 139.820251,
        place_description: '菅原道真公を祀り、「亀戸の天神さま」として親しまれています。太鼓橋と池、そして藤棚の景観が有名で、歌川広重の浮世絵にも描かれました。4月下旬から5月上旬の藤まつりは特に賑わいます。',
        place_photo_url: null as string | null,
        place_era_start: 1646 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 74,
        place_name: '護国寺',
        lat: 35.720230,
        lng: 139.726207,
        place_description: '徳川綱吉が母・桂昌院の願いにより建立した寺院です。本堂は元禄時代の建築が現存しており、都内でも貴重な江戸中期の建造物です。茶道の本山としても知られ、大規模な茶会が頻繁に催されています。',
        place_photo_url: null as string | null,
        place_era_start: 1681 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 75,
        place_name: '東京大神宮',
        lat: 35.700140,
        lng: 139.746864,
        place_description: '「東京のお伊勢さま」として親しまれる神社で、日本で初めて神前結婚式を行った場所として知られています。縁結びのパワースポットとして有名で、特に女性の参拝客が多く訪れます。',
        place_photo_url: null as string | null,
        place_era_start: 1880 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 76,
        place_name: '万世橋駅（旧駅舎）',
        lat: 35.697412,
        lng: 139.770281,
        place_description: 'かつて神田と御茶ノ水の間に存在した国鉄の駅です。辰野金吾設計の赤レンガ造りの豪華な駅舎でしたが、現在は廃止されています。遺構の一部を活用し、商業施設「マーチエキュート神田万世橋」として再生されました。',
        place_photo_url: null as string | null,
        place_era_start: 1912 as number | null,
        place_era_end: 1943 as number | null,
    },
    {
        place_id: 77,
        place_name: '築地市場（場内）',
        lat: 35.663162,
        lng: 139.769490,
        place_description: 'かつて世界最大の水産物取扱量を誇った中央卸売市場です。扇形の建物が特徴的で、早朝のマグロの競りは観光名所でもありました。2018年に豊洲へ移転し、83年の歴史に幕を閉じました。',
        place_photo_url: null as string | null,
        place_era_start: 1935 as number | null,
        place_era_end: 2018 as number | null,
    },
    {
        place_id: 78,
        place_name: '雑司ヶ谷鬼子母神堂',
        lat: 35.722513,
        lng: 139.713919,
        place_description: '安産・子育の神様として信仰を集めています。参道のケヤキ並木は樹齢400年を超え、江戸の情緒を残しています。境内にある駄菓子屋「上川口屋」は日本最古の駄菓子屋と言われ、創業は1781年です。',
        place_photo_url: null as string | null,
        place_era_start: 1578 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 79,
        place_name: '湯島聖堂',
        lat: 35.700940,
        lng: 139.766723,
        place_description: '徳川綱吉によって建てられた孔子廟であり、江戸幕府の学問所「昌平坂学問所」の跡地です。日本の学校教育発祥の地とされ、合格祈願の名所です。黒塗りの独特な建築様式が、他のお寺や神社とは異なる威厳を放ちます。',
        place_photo_url: null as string | null,
        place_era_start: 1690 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 80,
        place_name: '江戸城天守',
        lat: 35.686526,
        lng: 139.754378,
        place_description: 'かつて江戸城本丸にそびえ立っていた日本最大の天守閣です。五層六階の巨大な建築物で、金色のシャチホコが輝いていましたが、1657年の明暦の大火で焼失し、以降再建されることはありませんでした。現在は天守台（石垣）のみが残ります。',
        place_photo_url: null as string | null,
        place_era_start: 1607 as number | null, // 慶長度天守等の変遷あるが最初の天守として
        place_era_end: 1657 as number | null,
    },
    {
        place_id: 81,
        place_name: '東京ドームシティ',
        lat: 35.704253,
        lng: 139.753381,
        place_description: '東京ドームを中心とした都市型エンターテインメントエリアです。ジェットコースターや観覧車がある遊園地、スパ施設「ラクーア」、ホテルなどがあり、都心にいながら一日中遊べるスポットです。',
        place_photo_url: null as string | null,
        place_era_start: 2003 as number | null, // ラクーア開業等で現在の形に
        place_era_end: null as number | null,
    },
    {
        place_id: 82,
        place_name: 'サンシャイン水族館',
        lat: 35.728926,
        lng: 139.719602,
        place_description: 'サンシャインシティの屋上にある「天空のオアシス」をコンセプトにした水族館です。頭上の水槽を泳ぐ「空飛ぶペンギン」の展示が有名で、ビル群を背景に泳ぐペンギンの姿はここだけの光景です。',
        place_photo_url: null as string | null,
        place_era_start: 1978 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 83,
        place_name: '日本科学未来館',
        lat: 35.619335,
        lng: 139.776472,
        place_description: 'お台場にある国立の科学博物館です。宇宙飛行士の毛利衛氏が初代館長を務めました。地球ディスプレイ「ジオ・コスモス」や、ASIMOなどのロボット展示、最新のテクノロジーについて体験しながら学ぶことができます。',
        place_photo_url: null as string | null,
        place_era_start: 2001 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 84,
        place_name: 'かっぱ橋道具街',
        lat: 35.714494,
        lng: 139.789851,
        place_description: '浅草と上野の中間にある、調理器具や食器の問屋街です。プロ仕様の包丁から精巧な食品サンプルまで、食に関するあらゆる道具が揃います。巨大なコック像が目印で、料理好きや外国人観光客に人気のスポットです。',
        place_photo_url: null as string | null,
        place_era_start: 1912 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 85,
        place_name: '目黒雅叙園（ホテル雅叙園東京）',
        lat: 35.632204,
        lng: 139.714656,
        place_description: '「昭和の竜宮城」と称された日本初の総合結婚式場です。絢爛豪華な日本画や螺鈿細工で埋め尽くされた内装は圧巻で、特に「百段階段」は東京都の有形文化財に指定され、企画展などで公開されています。',
        place_photo_url: null as string | null,
        place_era_start: 1931 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 86,
        place_name: '歌舞伎町タワー',
        lat: 35.695325,
        lng: 139.700868,
        place_description: '2023年に新宿歌舞伎町に開業した超高層複合施設です。ホテル、映画館、劇場、ライブホールなどを備え、外観は噴水をイメージしています。ネオン輝く「新宿カブキhall」など、ナイトライフの新たな拠点です。',
        place_photo_url: null as string | null,
        place_era_start: 2023 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 87,
        place_name: '渋谷スカイ',
        lat: 35.658466,
        lng: 139.702257,
        place_description: '渋谷スクランブルスクエアの屋上にある展望施設です。地上約230mから360度のパノラマビューを楽しめ、スクランブル交差点を真上から見下ろせます。ガラス張りの角での撮影は、SNSで世界的に話題です。',
        place_photo_url: null as string | null,
        place_era_start: 2019 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 88,
        place_name: '神田古書店街',
        lat: 35.695574,
        lng: 139.759902,
        place_description: '神保町を中心とした世界最大級の古書店街です。約170軒の古書店が軒を連ね、文学、歴史、美術からサブカルチャーまで、あらゆるジャンルの本が見つかります。カレーの激戦区としても知られています。',
        place_photo_url: null as string | null,
        place_era_start: 1880 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 89,
        place_name: '江戸東京たてもの園',
        lat: 35.716182,
        lng: 139.513511,
        place_description: '小金井公園内にある野外博物館です。江戸時代から昭和初期までの歴史的建造物を移築・復元・展示しています。「千と千尋の神隠し」のモデルになったとされる銭湯や文具店などがあり、タイムスリップした気分を味わえます。',
        place_photo_url: null as string | null,
        place_era_start: 1993 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 90,
        place_name: '国立競技場（旧・1964年）',
        lat: 35.678072,
        lng: 139.713919,
        place_description: '1964年の東京オリンピックのメイン会場として使用された競技場です。数々のスポーツの歴史的瞬間やコンサートの舞台となりましたが、2020年大会に向けた建て替えのため2015年に解体されました。',
        place_photo_url: null as string | null,
        place_era_start: 1958 as number | null,
        place_era_end: 2015 as number | null,
    },
    {
        place_id: 91,
        place_name: '吉原大門（跡）',
        lat: 35.723788,
        lng: 139.796349,
        place_description: '江戸時代に公許の遊郭「吉原」の入り口にあった門の跡です。現在は「吉原大門」と書かれた交差点や柱が残るのみですが、かつての遊郭街の独特な区割りや、S字カーブの道（お歯黒どぶ跡）に歴史の痕跡を見ることができます。',
        place_photo_url: null as string | null,
        place_era_start: 1617 as number | null, // 吉原遊廓の開設
        place_era_end: 1958 as number | null, // 売春防止法施行による赤線廃止
    },
    {
        place_id: 92,
        place_name: '浅草花やしき',
        lat: 35.715340,
        lng: 139.794692,
        place_description: '1853年開園の日本最古の遊園地です。現存する日本最古の「ローラーコースター」は、民家の軒先をかすめるように走るスリルが人気です。レトロな雰囲気が漂い、浅草観光の定番スポットの一つです。',
        place_photo_url: null as string | null,
        place_era_start: 1853 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 93,
        place_name: '鈴本演芸場',
        lat: 35.708846,
        lng: 139.773347,
        place_description: '上野にある都内最古の寄席です。落語を中心に漫才、奇術、紙切りなどの色物芸が毎日上演されています。飲食物（アルコール含む）を持ち込んで、リラックスして江戸の笑いを楽しむことができます。',
        place_photo_url: null as string | null,
        place_era_start: 1857 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 94,
        place_name: '国立天文台三鷹キャンパス',
        lat: 35.675681,
        lng: 139.540899,
        place_description: '日本の天文学の中枢です。登録有形文化財の大赤道儀室や、アインシュタイン塔（太陽塔望遠鏡）など、歴史的な観測施設が緑豊かなキャンパス内に点在しており、見学コースとして一般公開されています。',
        place_photo_url: null as string | null,
        place_era_start: 1924 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 95,
        place_name: '井の頭自然文化園',
        lat: 35.701389,
        lng: 139.570778,
        place_description: '井の頭公園内にある動物園です。「リスの小径」では放し飼いのリスを間近で観察できます。かつて戦後最長の飼育記録を持ったアジアゾウの「はな子」が暮らしていた場所としても知られ、地域に愛される施設です。',
        place_photo_url: null as string | null,
        place_era_start: 1942 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 96,
        place_name: '思い出横丁',
        lat: 35.693081,
        lng: 139.699472,
        place_description: '新宿駅西口のガード沿いにある飲み屋街です。戦後の闇市の名残を留めており、狭い路地に焼き鳥屋やもつ焼き屋がひしめき合っています。昭和ノスタルジーを感じさせる独特の雰囲気があり、外国人観光客にも人気です。',
        place_photo_url: null as string | null,
        place_era_start: 1946 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 97,
        place_name: '迎賓館赤坂離宮和風別館（游心亭）',
        lat: 35.679549,
        lng: 139.732389,
        place_description: '谷口吉郎の設計による、迎賓館赤坂離宮の敷地内にある和風施設です。国賓に対して日本のおもてなしを行う場として1974年に新設されました。主庭の池や茶室が見事で、本館の西洋宮殿とは対照的な美しさを持っています。',
        place_photo_url: null as string | null,
        place_era_start: 1974 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 98,
        place_name: '旧新橋停車場',
        lat: 35.665675,
        lng: 139.761008,
        place_description: '1872年に開業した日本最初の鉄道ターミナル駅の外観を、当時と同じ場所に再現した建物です。現在は鉄道歴史展示室となっています。発掘調査で見つかった当時のプラットホームや線路の遺構も見学できます。',
        place_photo_url: null as string | null,
        place_era_start: 1872 as number | null, // オリジナルの開業年
        place_era_end: null as number | null, // 建物は復元だが施設として現存
    },
    {
        place_id: 99,
        place_name: '増上寺徳川将軍家墓所',
        lat: 35.657023,
        lng: 139.748366,
        place_description: '増上寺境内にある徳川将軍家の墓所です。かつては国宝級の霊廟建築が立ち並んでいましたが空襲で焼失しました。現在は2代秀忠、6代家宣など6人の将軍と、和宮（静寛院宮）などが静かに眠っています。',
        place_photo_url: null as string | null,
        place_era_start: 1632 as number | null, // 台徳院霊廟造営など
        place_era_end: null as number | null,
    },
    {
        place_id: 100,
        place_name: '東京駅ステーションギャラリー',
        lat: 35.681534,
        lng: 139.766060,
        place_description: '東京駅丸の内駅舎の中にある美術館です。国の重要文化財である駅舎の赤レンガ壁を展示室の壁面としてそのまま利用しているのが特徴で、歴史の重みを感じながらアート鑑賞ができるユニークな空間です。',
        place_photo_url: null as string | null,
        place_era_start: 1988 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 101,
        place_name: '東京工業大学すずかけ台キャンパス',
        lat: 35.51417560214643,
        lng: 139.48364376463735,
        place_description: '日本で一番頭のいい大学です。すずかけ台キャンパスではJ2,J3棟が一番高い建物であり、優秀な人ほど上の階に住んでいます。',
        place_photo_url: 'https://www.titech.ac.jp/public-relations/img/82-img-campus-invitation-suzukakedai02.jpg' as string | null,
        place_era_start: 1975 as number | null,
        place_era_end: 2024 as number | null,
    },
    {
        place_id: 102,
        place_name: '東京科学大学すずかけ台キャンパス',
        lat: 35.51417560214643,
        lng: 139.48364376463735,
        place_description: '東京科学大学（とうきょうかがくだいがく、英: Institute of Science Tokyo）は、東京都目黒区に本部を置く日本の国立大学である。略称はScience Tokyo、科学大。東京工業大学と東京医科歯科大学の統合により、2024年に設立された。',
        place_photo_url: 'https://www.titech.ac.jp/public-relations/img/82-img-campus-invitation-suzukakedai02.jpg' as string | null,
        place_era_start: 2024 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 103,
        place_name: '東京工業大学大岡山キャンパス',
        lat: 35.60485178683271,
        lng: 139.68385410808457,
        place_description: '昔から存在する有所ある日本で一番頭のいい大学です。',
        place_photo_url: null as string | null,
        place_era_start: 1924 as number | null,
        place_era_end: 2024 as number | null,
    },
    {
        place_id: 104,
        place_name: '東京科学大学大岡山キャンパス',
        lat: 35.60485178683271,
        lng: 139.68385410808457,
        place_description: '東京科学大学（とうきょうかがくだいがく、英: Institute of Science Tokyo）は、東京都目黒区に本部を置く日本の国立大学である。略称はScience Tokyo、科学大。東京工業大学と東京医科歯科大学の統合により、2024年に設立された。',
        place_photo_url: 'https://www.titech.ac.jp/public-relations/img/82-img-campus-invitation-ookayama01.jpg' as string | null,
        place_era_start: 2024 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 105,
        place_name: '東京科学大学 本館（時計台）',
        lat: 35.604851,
        lng: 139.683854,
        place_description: 'キャンパスのシンボルである時計台を持つ建物です。1934年（昭和9年）竣工。関東大震災後の復興建築として、鉄筋コンクリート造の堅牢さと、スクラッチタイル貼りのモダンな外観を兼ね備えています。',
        place_photo_url: 'https://www.titech.ac.jp/public-relations/img/82-img-campus-invitation-ookayama01.jpg' as string | null,
        place_era_start: 1934 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 106,
        place_name: '東京科学大学 博物館（百年記念館）',
        lat: 35.606200,
        lng: 139.684500,
        place_description: '正門を入ってすぐに見える、カマボコ型の銀色の建物です。篠原一男の設計で、その形状から「ガンダム」とも呼ばれます。大学の歴史資料や、フェライトコアなどのノーベル賞級の発明品が展示されています。',
        place_photo_url: 'https://www.titech.ac.jp/public-relations/img/82-img-campus-invitation-ookayama03.jpg' as string | null,
        place_era_start: 1987 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 107,
        place_name: '東京科学大学 附属図書館（チーズケーキ）',
        lat: 35.605500,
        lng: 139.684100,
        place_description: '三角形の鋭角なガラス張りの外観から、学生の間で「チーズケーキ」の愛称で親しまれています。建物の大半が地下に埋まっており、地下空間は「知の洞窟」のような静寂な学習スペースとなっています。',
        place_photo_url: 'https://www.titech.ac.jp/public-relations/img/82-img-campus-invitation-ookayama02.jpg' as string | null,
        place_era_start: 2011 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 108,
        place_name: 'Taki Plaza（タキ・プラザ）',
        lat: 35.605200,
        lng: 139.684800,
        place_description: '隈研吾の設計による学生交流拠点です。「丘」のような形状をしており、建物の屋上がそのまま階段状の広場や緑地になっています。地下で図書館と接続しており、キャンパスの新しいランドマークです。',
        place_photo_url: 'https://admissions.titech.ac.jp/public-relations/img/242-takiplaza-title.jpg' as string | null,
        place_era_start: 2020 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 109,
        place_name: '70周年記念講堂',
        lat: 35.603800,
        lng: 139.683500,
        place_description: '谷口吉郎の設計による、独特の折板構造の屋根を持つ講堂です。地下にはかつて学生食堂があり、多くの学生の胃袋を支えました。現在はリノベーションされ、地域のイベントなどにも活用されています。',
        place_photo_url: 'https://www.titech.ac.jp/public-relations/img/82-pic-cultural-properties10.jpg' as string | null,
        place_era_start: 1958 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 110,
        place_name: '西1号館',
        lat: 35.603500,
        lng: 139.682800,
        place_description: '本館と同様に戦前の1931年に建てられた古い校舎です。重厚なスクラッチタイルの外観が特徴で、現在も講義室や研究室として現役で使用されています。登録有形文化財に登録されています。',
        place_photo_url: 'https://www.titech.ac.jp/public-relations/img/82-pic-cultural-properties01.jpg' as string | null,
        place_era_start: 1931 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 111,
        place_name: 'ワグネル記念碑',
        lat: 35.60716749164708,
        lng: 139.681590509955,
        place_description: 'ゴットフリート・ワグネルは本学の前身である東京職工学校の創立に関わり、本学草創期の教育・研究に貢献しました。東京職工学校に「陶器玻璃工科」を設置し、日本で初めて陶磁器やガラスの専門教育・研究を進めました。大岡山北地区のひょうたん池近くに設置されています。',
        place_photo_url: 'https://www.titech.ac.jp/public-relations/img/img-index14.jpg' as string | null,
        place_era_start: 1937 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 112,
        place_name: 'かんらん岩の野外展示',
        lat: 35.601400,
        lng: 139.681800,
        place_description: '石川台地区の道路沿いに、無造作に置かれた巨大な岩石群です。これらは地球のマントルを構成する「かんらん岩」で、研究用に採取された貴重な標本が野外展示されています。マニアにはたまらないスポットです。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 113,
        place_name: '大岡山地下駅',
        lat: 35.607421,
        lng: 139.685627,
        place_description: '東急目黒線と大井町線が乗り入れる地下駅です。1997年に地下化されました。地下にありながら、広々とした吹き抜け空間を持ち、ホームドアの発車音が方向別に異なるなど、ユニークな特徴があります。',
        place_photo_url: 'https://www.tokyu.co.jp/mediacms/upload/MG_06_OM_08_Ookayama_00_048679d0c3.jpg' as string | null,
        place_era_start: 1997 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 114,
        place_name: '東急病院',
        lat: 35.607421,
        lng: 139.685627,
        place_description: '日本でも珍しい「駅の真上にある総合病院」です。大岡山駅の直上に建設されており、線路の防振対策が施されているため、入院患者も電車の振動を感じにくい構造になっています。',
        place_photo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Tokyu_Hospital.jpg/960px-Tokyu_Hospital.jpg' as string | null,
        place_era_start: 2007 as number | null, // 建替え新装開院
        place_era_end: null as number | null,
    },
    {
        place_id: 115,
        place_name: '旧大岡山駅舎（地上駅時代）',
        lat: 35.607421,
        lng: 139.685627,
        place_description: 'かつて地上にあった頃の駅舎です。目蒲線と大井町線が交差し、踏切の遮断時間が長いことでも知られていました。地下化工事に伴い姿を消しましたが、駅前の風景は劇的に変化しました。',
        place_photo_url: null as string | null,
        place_era_start: 1923 as number | null,
        place_era_end: 1997 as number | null,
    },

    // 116-125: 洗足池・勝海舟・北千束エリア
    {
        place_id: 116,
        place_name: '洗足池公園',
        lat: 35.601556,
        lng: 139.691764,
        place_description: '都内屈指の広さを誇る淡水池のある公園です。湧き水を水源としており、ボート遊びが楽しめます。桜の名所としても有名で、池に架かる三連の「池月橋」からの眺めは絶景です。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null, // 古来より存在
        place_era_end: null as number | null,
    },
    {
        place_id: 117,
        place_name: '勝海舟記念館（旧清明文庫）',
        lat: 35.600600,
        lng: 139.692400,
        place_description: '洗足池畔にある、勝海舟の功績を伝える記念館です。建物は昭和初期に建てられた「清明文庫」を改修したもので、ネオ・ゴシック様式の意匠が特徴的です。国の登録有形文化財です。',
        place_photo_url: null as string | null,
        place_era_start: 1933 as number | null, // 建物竣工
        place_era_end: null as number | null,
    },
    {
        place_id: 118,
        place_name: '勝海舟夫妻の墓',
        lat: 35.600300,
        lng: 139.692100,
        place_description: '晩年を洗足池畔の「千束軒」で過ごした勝海舟とその妻・民子の墓所です。海舟は「ここ（洗足池）が一番好きだ」と語り、遺言通りこの地に葬られました。ひっそりと静かな木立の中にあります。',
        place_photo_url: null as string | null,
        place_era_start: 1899 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 119,
        place_name: '西郷隆盛留魂詩碑',
        lat: 35.600350,
        lng: 139.692150,
        place_description: '勝海舟が、西南戦争で倒れた盟友・西郷隆盛を悼んで建てた石碑です。元々は葛飾区の浄光寺にありましたが、海舟の遺志により大正時代にこの場所へ移設されました。',
        place_photo_url: null as string | null,
        place_era_start: 1883 as number | null, // 建立年
        place_era_end: null as number | null,
    },
    {
        place_id: 120,
        place_name: '御松庵 妙福寺',
        lat: 35.601800,
        lng: 139.693200,
        place_description: '日蓮聖人が身延山へ向かう途中、洗足池で休息し、袈裟を松の木に掛けて洗ったという伝承が残る寺院です。「袈裟掛けの松」の3代目が境内にあり、地名「洗足」の由来の一つとされています。',
        place_photo_url: null as string | null,
        place_era_start: 1282 as number | null, // 伝承の起源
        place_era_end: null as number | null,
    },
    {
        place_id: 121,
        place_name: '千束八幡神社',
        lat: 35.602500,
        lng: 139.690500,
        place_description: '源頼朝が宿営した際、名馬「池月」が現れたという伝説が残る神社です。「池月」の銅像があり、勝海舟直筆の額も保存されています。洗足池を見下ろす高台に鎮座しています。',
        place_photo_url: null as string | null,
        place_era_start: 860 as number | null, // 創建伝承
        place_era_end: null as number | null,
    },
    {
        place_id: 122,
        place_name: '清水窪弁財天',
        lat: 35.609500,
        lng: 139.687200,
        place_description: '大岡山駅から徒歩数分の住宅街にある湧水スポットです。東京の名湧水57選に選ばれており、ここの湧き水は暗渠を通って洗足池に注いでいます。小さな滝と池があり、別世界のような静けさです。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 123,
        place_name: '大岡山北口商店街',
        lat: 35.608000,
        lng: 139.686000,
        place_description: '駅北口に続く活気ある商店街です。学生街と住宅街の両方の顔を持ち、老舗の定食屋から新しいカフェまで並びます。清水窪弁財天への散策ルートの入り口でもあります。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 124,
        place_name: '石川神社（神明社）',
        lat: 35.601200,
        lng: 139.682500,
        place_description: '東工大キャンパスの南側の谷底に位置する神社です。急な「神明坂」の途中にあり、かつての石川村の鎮守でした。周辺はすり鉢状の地形になっており、地形マニアには興味深い場所です。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 125,
        place_name: '石川村郷倉',
        lat: 35.600800,
        lng: 139.683000,
        place_description: '江戸時代に年貢米や飢饉への備蓄米を保管していた共同倉庫です。大田区内に現存する唯一の郷倉で、区の文化財に指定されています。当時の農村の生活を伝える貴重な遺構です。',
        place_photo_url: null as string | null,
        place_era_start: 1800 as number | null, // 推定江戸後期
        place_era_end: null as number | null,
    },

    // 126-135: 緑が丘・自由が丘・川と緑道
    {
        place_id: 126,
        place_name: '緑が丘駅',
        lat: 35.606399,
        lng: 139.679124,
        place_description: '東急大井町線の駅です。駅舎の屋根や鉄骨が緑色に塗られているのが特徴的です。駅のすぐ南側を九品仏川緑道（暗渠）が通っており、春には桜のトンネルとなります。',
        place_photo_url: null as string | null,
        place_era_start: 1929 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 127,
        place_name: '九品仏川緑道',
        lat: 35.606100,
        lng: 139.678000,
        place_description: 'かつての九品仏川を暗渠化して整備された遊歩道です。緑が丘駅から自由が丘方面へ続いており、ベンチが多く設置され、市民の憩いの場となっています。',
        place_photo_url: null as string | null,
        place_era_start: 1974 as number | null, // 暗渠化・緑道整備
        place_era_end: null as number | null,
    },
    {
        place_id: 128,
        place_name: '呑川本流緑道',
        lat: 35.612000,
        lng: 139.675000,
        place_description: '都立大学駅方面から流れてくる呑川の暗渠緑道です。春は桜並木が見事で、特に工大橋付近の桜は圧巻です。東工大キャンパスの北側境界を形成しています。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 129,
        place_name: '大岡山公園',
        lat: 35.603000,
        lng: 139.686500,
        place_description: '区界にある公園で、目黒区側は大岡山公園、大田区側は石川町に関連する名称で呼ばれることがあります。こぢんまりとしていますが、起伏に富んだ地形を利用しており、地域の子供たちの遊び場です。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 130,
        place_name: '神明坂',
        lat: 35.601500,
        lng: 139.683000,
        place_description: '大田区石川町へ下る急坂です。坂の下に石川神社（神明社）があることが名前の由来です。坂の上からは視界が開け、武蔵野台地のへりであることを実感できる地形スポットです。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 131,
        place_name: '稲荷坂',
        lat: 35.603500,
        lng: 139.688000,
        place_description: '洗足池の西側、北千束から上る坂道です。かつて坂の途中に稲荷社があったことに由来します。拡幅されていますが、古くからある九品仏へ通じる道の一部でした。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 132,
        place_name: '中原街道（旧道跡）',
        lat: 35.600000,
        lng: 139.688000,
        place_description: '江戸と平塚中原を結んだ古街道です。現在の広い中原街道に対し、洗足池周辺など一部に旧道の面影を残す細い道が並行しています。かつては徳川将軍も鷹狩りの際に行き来しました。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 133,
        place_name: '洗足駅',
        lat: 35.610500,
        lng: 139.695000,
        place_description: '目黒線の駅で、日本初の「田園都市」として開発された洗足田園都市の玄関口です。駅前のいちょう並木は開発当時の面影を残しており、閑静な住宅街が広がっています。',
        place_photo_url: null as string | null,
        place_era_start: 1923 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 134,
        place_name: '北千束駅',
        lat: 35.606500,
        lng: 139.692500,
        place_description: '大井町線の駅です。高架駅のように見えますが、地形の関係で駅の一部が盛土や切通しのようになっています。洗足池まで徒歩数分でアクセス可能です。',
        place_photo_url: null as string | null,
        place_era_start: 1928 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 135,
        place_name: '長原駅',
        lat: 35.602500,
        lng: 139.698000,
        place_description: '池上線の駅で、かつては地上駅でしたが現在は地下化されています。駅舎の上にはスーパーマーケットなどが建ち並ぶ「長原東急ストア」があり、地域密着型の駅です。',
        place_photo_url: null as string | null,
        place_era_start: 1927 as number | null,
        place_era_end: null as number | null,
    },

    // 136-145: 少し足を延ばして（碑文谷・都立大跡地など）＆マニアック
    {
        place_id: 136,
        place_name: 'カトリック碑文谷教会（サレジオ教会）',
        lat: 35.620500,
        lng: 139.689000,
        place_description: '美しいロマネスク様式の大聖堂を持つ教会です。36メートルの鐘塔は地域のランドマークとなっており、多くの著名人が挙式したことでも有名です。内部のステンドグラスやフレスコ画は圧巻です。',
        place_photo_url: null as string | null,
        place_era_start: 1954 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 137,
        place_name: 'すずめのお宿緑地公園',
        lat: 35.618500,
        lng: 139.686000,
        place_description: 'かつて数千羽のスズメがねぐらにしていた竹林が残る公園です。園内には目黒区の古民家（旧栗山家主屋）が移築復元されており、江戸時代の農家の暮らしを垣間見ることができます。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 138,
        place_name: 'めぐろ区民キャンパス（旧都立大学跡地）',
        lat: 35.617000,
        lng: 139.673000,
        place_description: 'かつて東京都立大学（現・都立大）のキャンパスがあった場所です。現在は「めぐろパーシモンホール」や図書館などの複合施設になっています。「パーシモン」は地名である柿の木坂に由来します。',
        place_photo_url: null as string | null,
        place_era_start: 2002 as number | null, // 施設開業
        place_era_end: null as number | null,
    },
    {
        place_id: 139,
        place_name: '東京都立大学（目黒キャンパス）',
        lat: 35.617000,
        lng: 139.673000,
        place_description: '1991年までこの地にあった公立大学です。八王子市南大沢への移転に伴い閉鎖されましたが、周辺の「都立大学駅」という駅名にその名残を留めています。',
        place_photo_url: null as string | null,
        place_era_start: 1949 as number | null, // 新制大学として
        place_era_end: 1991 as number | null,
    },
    {
        place_id: 140,
        place_name: '円融寺',
        lat: 35.615000,
        lng: 139.691000,
        place_description: '平安時代の慈覚大師による創建と伝わる天台宗の古刹です。室町時代建立の「釈迦堂」は、東京23区内では最古の木造建築の一つとされ、国の重要文化財に指定されています。',
        place_photo_url: null as string | null,
        place_era_start: 853 as number | null, // 伝承
        place_era_end: null as number | null,
    },
    {
        place_id: 141,
        place_name: '碑文谷八幡宮',
        lat: 35.610800,
        lng: 139.686500,
        place_description: '碑文谷の地名の由来となった「碑文石」が保存されている神社です。参道の桜並木が見事で、春には桜のトンネルとなります。古くから地域の守り神として崇敬されています。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 142,
        place_name: '立源寺',
        lat: 35.613000,
        lng: 139.684000,
        place_description: '目黒区にある寺院で、かつてはサツマイモ栽培で知られた地域にあります。境内には古い石碑などが残り、静かな佇まいを見せています。現代的な葬祭施設も併設されています。',
        place_photo_url: null as string | null,
        place_era_start: 1624 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 143,
        place_name: '大井町線・目黒線 交差地点跡',
        lat: 35.607400,
        lng: 139.685600,
        place_description: '地下化される前、大岡山駅のすぐ西側で目蒲線と大井町線の線路が平面交差（または複雑な分岐）をしていました。現在は地下で立体交差・対面乗り換えが可能になり、当時の線路の喧騒は過去のものとなりました。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: 1997 as number | null,
    },
    {
        place_id: 144,
        place_name: '目黒線の地上線路跡（緑道）',
        lat: 35.613500,
        lng: 139.693000,
        place_description: '武蔵小山から洗足、大岡山にかけての地下化に伴い、地上にあった線路跡の一部は緑道や遊歩道として整備されました。一部区間では、かつて電車が走っていた緩やかなカーブを歩いて体感できます。',
        place_photo_url: null as string | null,
        place_era_start: 2006 as number | null, // 地下化後の整備
        place_era_end: null as number | null,
    },
    {
        place_id: 145,
        place_name: '奥沢神社',
        lat: 35.604000,
        lng: 139.671000,
        place_description: '世田谷区奥沢にある神社で、鳥居に藁で作られた大蛇が巻き付いている「厄除けの大蛇」で有名です。毎年9月の例大祭では、新しい大蛇が作られ町内を巡行します。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },

    // 146-152: さらにニッチ・マニアック
    {
        place_id: 146,
        place_name: '大岡山配水塔（存在せず）',
        lat: 35.606000,
        lng: 139.685000,
        place_description: '昭和初期、大岡山の高台にはかつて水道タンク（配水塔）が存在したと言われています。現在は痕跡を見つけることは困難ですが、古地図や古い写真にはその姿が記録されている幻のランドマークです。',
        place_photo_url: null as string | null,
        place_era_start: 1930 as number | null, // 推定
        place_era_end: 1960 as number | null, // 推定
    },
    {
        place_id: 147,
        place_name: 'TSUTAYA大岡山店（駅地下時代）',
        lat: 35.607421,
        lng: 139.685627,
        place_description: '大岡山駅の地下化工事完了後、改札外の地下空間に一時的に存在したレンタルショップです。広大な地下スペースを活用した店舗でしたが、その後の駅ビル開発や東急病院建設に伴い閉店しました。地元民の記憶に残るスポットです。',
        place_photo_url: null as string | null,
        place_era_start: 1997 as number | null,
        place_era_end: 2007 as number | null,
    },
    {
        place_id: 148,
        place_name: 'つばめグリル（発祥の地近隣）',
        lat: 35.606000,
        lng: 139.686000,
        place_description: 'ハンブルグステーキで有名な「つばめグリル」は、新橋が1号店ですが、創業者が大岡山周辺に住んでいた、あるいは地域の「つばめ」という名称（特急つばめ由来とも）が、東工大のシンボルマークとも奇妙にリンクする面白い偶然があります。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 149,
        place_name: '鉄飛坂（てっぴざか）',
        lat: 35.614000,
        lng: 139.670000,
        place_description: '目黒通りから呑川に向かって下る急坂です。源頼朝がここで馬を走らせたという伝説や、赤土が露出していたことから「鉄」の色に見えたなど、名前の由来には諸説ある歴史的な坂道です。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 150,
        place_name: '宮野古民家自然園',
        lat: 35.610000,
        lng: 139.697000,
        place_description: '目黒区原町にある、江戸時代の農家建築を保存した施設です。屋敷林がそのまま残されており、かつての目黒の農村風景を今に伝えています。',
        place_photo_url: null as string | null,
        place_era_start: 1700 as number | null, // 江戸中期建築
        place_era_end: null as number | null,
    },
    {
        place_id: 151,
        place_name: '目黒本町 福祉のまち（旧競馬場跡関連？）',
        lat: 35.623000,
        lng: 139.698000,
        place_description: '大岡山からは少し離れますが、目黒通り沿いにはかつて「目黒競馬場」がありました。その広大な跡地の一部は、現在の元競馬場前バス停付近や、住宅街の独特なカーブとして痕跡を留めています。',
        place_photo_url: null as string | null,
        place_era_start: 1907 as number | null,
        place_era_end: 1933 as number | null,
    },
    {
        place_id: 152,
        place_name: '羅漢寺川緑道',
        lat: 35.626000,
        lng: 139.699000,
        place_description: '目黒不動尊の近くを流れていた羅漢寺川の暗渠です。現在は遊歩道として整備されています。大岡山周辺から少し足を延ばした散策コースとして、地形マニアに人気があります。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
];