export const places = [
    {
        place_id: 1,
        place_name: '東京タワー',
        lat: 35.6585805,
        lng: 139.7454329,
        place_description: '1958年に完成した高さ333mの総合電波塔です。長年東京のシンボルとして親しまれ、その赤と白の美しいフォルムはランドマークとして定着しています。メインデッキからは関東平野を一望でき、夜のライトアップも季節ごとに変化します。',
        place_photo_url: null as string | null,
        place_era_start: 1958 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 2,
        place_name: '東京スカイツリー',
        lat: 35.7100627,
        lng: 139.8107004,
        place_description: '2012年に開業した高さ634mを誇る世界一高い自立式電波塔です。天望デッキと天望回廊からは、晴天時には富士山まで見渡せる絶景が広がります。足元には商業施設「東京ソラマチ」があり、ショッピングや水族館も楽しめます。',
        place_photo_url: null as string | null,
        place_era_start: 2012 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 3,
        place_name: '浅草寺',
        lat: 35.7147651,
        lng: 139.7966553,
        place_description: '628年に創建されたと伝わる都内最古の寺院です。「雷門」の大提灯や、土産物店が立ち並ぶ「仲見世通り」は世界的にも有名です。江戸時代には徳川将軍家の祈願所として栄え、現在も年間を通して多くの参拝客で賑わいます。',
        place_photo_url: null as string | null,
        place_era_start: 628 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 4,
        place_name: '明治神宮',
        lat: 35.6763976,
        lng: 139.6993259,
        place_description: '明治天皇と昭憲皇太后をお祀りする神社です。1920年に創建され、広大な鎮守の杜は全国からの献木によって造成されました。都会の真ん中にありながら豊かな自然が広がり、初詣の参拝者数は日本一を誇ります。',
        place_photo_url: null as string | null,
        place_era_start: 1920 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 5,
        place_name: '皇居（旧江戸城）',
        lat: 35.685175,
        lng: 139.7527995,
        place_description: 'かつての江戸城跡に位置する天皇陛下の御所です。二重橋や伏見櫓などの歴史的建造物が残り、東御苑は一般公開されています。周囲のお濠や石垣は、徳川幕府の権威と当時の築城技術の高さを今に伝えています。',
        place_photo_url: null as string | null,
        place_era_start: 1457 as number | null, // 太田道灌による築城開始
        place_era_end: null as number | null,
    },
    {
        place_id: 6,
        place_name: '東京駅（丸の内駅舎）',
        lat: 35.6812362,
        lng: 139.7671248,
        place_description: '1914年に開業した日本の鉄道網の起点となるターミナル駅です。辰野金吾設計による赤レンガ造りの駅舎は、国の重要文化財に指定されています。2012年に復原工事が完了し、創建当時の美しいドーム屋根が蘇りました。',
        place_photo_url: null as string | null,
        place_era_start: 1914 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 7,
        place_name: '上野恩賜公園',
        lat: 35.7140708,
        lng: 139.7741094,
        place_description: '1873年に指定された日本最初の公園の一つです。園内には博物館、美術館、動物園、芸術大学などが集積しており、文化・芸術の拠点となっています。春には桜の名所として、多くの花見客で賑わいを見せます。',
        place_photo_url: null as string | null,
        place_era_start: 1873 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 8,
        place_name: '新宿御苑',
        lat: 35.6851774,
        lng: 139.7100516,
        place_description: '江戸時代の信州高遠藩主内藤家の下屋敷跡に造られた国民公園です。フランス式整形庭園、イギリス風景式庭園、日本庭園が巧みに組み合わされています。春の桜、秋の紅葉など、四季折々の自然を楽しむことができます。',
        place_photo_url: null as string | null,
        place_era_start: 1906 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 9,
        place_name: '渋谷スクランブル交差点',
        lat: 35.659482,
        lng: 139.700553,
        place_description: '世界で最も有名な交差点の一つと言われ、一度の青信号で最大3000人が横断するとも言われます。巨大な広告ビジョンと人波が織りなす風景は、現代の東京のエネルギーを象徴するスポットとして海外からも注目されています。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 10,
        place_name: '築地場外市場',
        lat: 35.6654865,
        lng: 139.7706668,
        place_description: 'かつての中央卸売市場に隣接して発展した商店街です。市場移転後も「食のまち」としての活気は健在で、新鮮な海産物、乾物、調理道具などを扱う専門店が密集しています。食べ歩きや寿司の名店を目当てに多くの人が訪れます。',
        place_photo_url: null as string | null,
        place_era_start: 1935 as number | null,
        place_era_end: null as number | null,
    },

    // 11-20: 文化施設・美術館・博物館
    {
        place_id: 11,
        place_name: '東京国立博物館',
        lat: 35.7187848,
        lng: 139.7764831,
        place_description: '1872年に創設された日本最古の博物館です。日本および東洋の美術・考古など多岐にわたる文化財を収蔵・展示しています。本館、表慶館、東洋館など、建物自体も歴史的価値が高く、重要文化財に指定されているものもあります。',
        place_photo_url: null as string | null,
        place_era_start: 1872 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 12,
        place_name: '三鷹の森ジブリ美術館',
        lat: 35.696238,
        lng: 139.5704317,
        place_description: 'スタジオジブリ作品の世界観を体験できる美術館です。宮崎駿監督がデザインを手がけ、「迷子になろうよ、いっしょに。」をコンセプトにしています。館内では短編映画の上映や、制作資料の展示が行われています。',
        place_photo_url: null as string | null,
        place_era_start: 2001 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 13,
        place_name: '国立新美術館',
        lat: 35.6652631,
        lng: 139.7263725,
        place_description: '黒川紀章設計による波打つようなガラスのカーテンウォールが印象的な美術館です。コレクションを持たず、国内最大級の展示スペースを生かして多彩な企画展や公募展を開催しています。六本木のアートトライアングルの一角です。',
        place_photo_url: null as string | null,
        place_era_start: 2007 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 14,
        place_name: '江戸東京博物館',
        lat: 35.6963842,
        lng: 139.7964321,
        place_description: '江戸から現代の東京に至る歴史と文化を展示する博物館です。実物大で復元された日本橋や中村座、当時の町並みの模型などを通じて、庶民の生活や都市の変遷を体感的に学ぶことができます。（※大規模改修中の場合あり）',
        place_photo_url: null as string | null,
        place_era_start: 1993 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 15,
        place_name: '国立科学博物館',
        lat: 35.716335,
        lng: 139.7763878,
        place_description: '1877年に設立された日本唯一の国立総合科学博物館です。「日本館」と「地球館」があり、忠犬ハチ公の剥製から恐竜の骨格標本、最新の科学技術まで、自然史と科学技術史に関する膨大な資料を展示しています。',
        place_photo_url: null as string | null,
        place_era_start: 1877 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 16,
        place_name: '根津美術館',
        lat: 35.662243,
        lng: 139.718873,
        place_description: '実業家・初代根津嘉一郎の古美術コレクションを展示するために設立されました。隈研吾設計の和風モダンな本館と、都心とは思えない静寂に包まれた広大な日本庭園が調和しており、国宝「燕子花図屏風」の所蔵で知られます。',
        place_photo_url: null as string | null,
        place_era_start: 1941 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 17,
        place_name: '森ビル デジタルアート ミュージアム',
        lat: 35.6599708,
        lng: 139.743141,
        place_description: 'アート集団チームラボによる「地図のないミュージアム」です。境界のないアート作品群が部屋から出て移動し、他の作品と影響し合いながら融合します。身体ごと没入できる新しい形のアート体験を提供しています。',
        place_photo_url: null as string | null,
        place_era_start: 2018 as number | null, // お台場開業年、現在は麻布台ヒルズへ移転
        place_era_end: null as number | null,
    },
    {
        place_id: 18,
        place_name: '迎賓館赤坂離宮',
        lat: 35.6803273,
        lng: 139.7291882,
        place_description: '日本唯一のネオ・バロック様式の西洋風宮殿建築です。明治時代に東宮御所として建設され、現在は世界各国の国王や大統領などをお迎えする外交の舞台となっています。国宝に指定されており、一般公開も行われています。',
        place_photo_url: null as string | null,
        place_era_start: 1909 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 19,
        place_name: '東京都庁舎',
        lat: 35.6896342,
        lng: 139.6921007,
        place_description: '丹下健三設計による新宿副都心のシンボルです。第一本庁舎にある南北の展望室は無料で開放されており、地上202mの高さから東京の街並みを一望できます。夜景スポットとしても人気があります。',
        place_photo_url: null as string | null,
        place_era_start: 1991 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 20,
        place_name: '歌舞伎座',
        lat: 35.669537,
        lng: 139.767784,
        place_description: '世界で唯一の歌舞伎専門劇場です。現在の建物は第五期で、伝統的な桃山様式の外観を残しつつ、背後に高層オフィスビルを併設した複合施設となっています。一幕見席もあり、気軽に伝統芸能に触れることができます。',
        place_photo_url: null as string | null,
        place_era_start: 1889 as number | null, // 初代開場
        place_era_end: null as number | null,
    },

    // 21-30: 神社仏閣・歴史（追加）
    {
        place_id: 21,
        place_name: '神田明神',
        lat: 35.702028,
        lng: 139.7679307,
        place_description: '730年創建と伝わる、江戸総鎮守として崇敬される神社です。神田、日本橋、秋葉原、大手町などの氏神様であり、商売繁盛や縁結びのご利益で知られます。秋葉原に近いため、ITお守りなども授与されています。',
        place_photo_url: null as string | null,
        place_era_start: 730 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 22,
        place_name: '靖国神社',
        lat: 35.6942023,
        lng: 139.7436668,
        place_description: '明治維新以降の国事に殉じた人々の霊を祀る神社です。境内にあるソメイヨシノの標本木は、気象庁が東京の桜の開花宣言を行う基準木として知られています。遊就館では遺品や史資料を展示しています。',
        place_photo_url: null as string | null,
        place_era_start: 1869 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 23,
        place_name: '増上寺',
        lat: 35.657418,
        lng: 139.748227,
        place_description: '浄土宗の七大本山の一つで、徳川将軍家の菩提寺です。東京タワーのすぐ足元に位置し、朱塗りの三解脱門と近代的なタワーのコントラストが特徴的です。境内には徳川将軍家の墓所があります。',
        place_photo_url: null as string | null,
        place_era_start: 1393 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 24,
        place_name: '湯島天満宮',
        lat: 35.707833,
        lng: 139.768407,
        place_description: '学問の神様である菅原道真公を祀る神社で、通称「湯島天神」と呼ばれます。受験シーズンには多くの学生が合格祈願に訪れます。また、江戸時代から梅の名所としても知られ、春には梅まつりが開催されます。',
        place_photo_url: null as string | null,
        place_era_start: 458 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 25,
        place_name: '富岡八幡宮',
        lat: 35.671911,
        lng: 139.799659,
        place_description: '江戸最大の八幡宮であり、江戸勧進相撲発祥の地として知られます。境内には横綱力士碑などの相撲関連の石碑が多くあります。夏に行われる「深川八幡祭り」は江戸三大祭りの一つに数えられ、水掛け祭りとして有名です。',
        place_photo_url: null as string | null,
        place_era_start: 1627 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 26,
        place_name: '浜離宮恩賜庭園',
        lat: 35.659666,
        lng: 139.763413,
        place_description: '江戸時代の代表的な大名庭園です。海水を引き入れた「潮入の池」があり、潮の干満によって景色の変化を楽しめます。園内の茶屋では抹茶を楽しむことができ、周囲の高層ビル群と庭園の対比が東京らしい景観です。',
        place_photo_url: null as string | null,
        place_era_start: 1654 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 27,
        place_name: '小石川後楽園',
        lat: 35.705193,
        lng: 139.749007,
        place_description: '水戸徳川家の上屋敷内に造られた回遊式築山泉水庭園です。中国の儒教思想の影響を色濃く受けており、「円月橋」など中国の景勝地を模した景観が見られます。国の特別史跡および特別名勝に指定されています。',
        place_photo_url: null as string | null,
        place_era_start: 1629 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 28,
        place_name: '日枝神社',
        lat: 35.674591,
        lng: 139.740228,
        place_description: '永田町に鎮座し、江戸城の鎮守神として崇められてきました。「山王さん」の愛称で親しまれ、6月の山王祭は天下祭として有名です。社殿へ続く階段にはエスカレーターが設置されており、近代的な設備も特徴です。',
        place_photo_url: null as string | null,
        place_era_start: 1478 as number | null, // 文明10年に太田道灌が勧請
        place_era_end: null as number | null,
    },
    {
        place_id: 29,
        place_name: '豪徳寺',
        lat: 35.648347,
        lng: 139.646845,
        place_description: '世田谷区にある曹洞宗の寺院で、井伊家の菩提寺です。「招き猫発祥の地」の一つとされ、奉納された数千体の招き猫が並ぶ「招猫殿」は圧巻の光景です。海外からの観光客にも人気のフォトスポットとなっています。',
        place_photo_url: null as string | null,
        place_era_start: 1480 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 30,
        place_name: '日本橋',
        lat: 35.684058,
        lng: 139.774501,
        place_description: '五街道の起点として江戸の交通の中心であった橋です。現在の橋は1911年に完成した石造二連アーチ橋で、重要文化財です。橋の中央には「日本国道路元標」があり、日本の道路網の始点であることを示しています。',
        place_photo_url: null as string | null,
        place_era_start: 1603 as number | null,
        place_era_end: null as number | null,
    },

    // 31-40: 商業・エンタメ・自然
    {
        place_id: 31,
        place_name: '六本木ヒルズ',
        lat: 35.660464,
        lng: 139.729249,
        place_description: 'オフィス、住宅、ホテル、美術館、映画館などが集約された複合都市です。中心となる森タワーの展望台「東京シティビュー」からは、東京タワーを間近に見下ろす絶景が楽しめます。',
        place_photo_url: null as string | null,
        place_era_start: 2003 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 32,
        place_name: 'お台場海浜公園',
        lat: 35.629392,
        lng: 139.775358,
        place_description: '東京湾に面した人工の砂浜と公園です。レインボーブリッジや対岸の都心のビル群を一望でき、特に夕暮れから夜景の時間帯が美しいです。自由の女神像があり、デートスポットや家族連れの憩いの場として人気です。',
        place_photo_url: null as string | null,
        place_era_start: 1996 as number | null, // 一部開園はもっと前だがリニューアル等含む
        place_era_end: null as number | null,
    },
    {
        place_id: 33,
        place_name: '井の頭恩賜公園',
        lat: 35.699709,
        lng: 139.573215,
        place_description: '武蔵野の面影を残す緑豊かな公園です。中央の井の頭池ではボート遊びができ、春は桜が池の水面に映り込みます。動物園（自然文化園）が併設されており、吉祥寺の街とも隣接しているため、散策に最適です。',
        place_photo_url: null as string | null,
        place_era_start: 1917 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 34,
        place_name: '竹下通り',
        lat: 35.671449,
        lng: 139.704273,
        place_description: '原宿駅前から続く商店街で、日本の「カワイイ」カルチャーの発信地です。クレープ店や個性的なファッションショップが軒を連ね、常に若者や観光客で溢れています。最新の流行を肌で感じることができるスポットです。',
        place_photo_url: null as string | null,
        place_era_start: 1970 as number | null, // 歩行者天国開始頃から若者の街へ
        place_era_end: null as number | null,
    },
    {
        place_id: 35,
        place_name: 'アメ横商店街',
        lat: 35.708892,
        lng: 139.774439,
        place_description: '上野駅から御徒町駅の間の高架下に広がる商店街です。戦後の闇市を起源とし、現在も鮮魚、乾物、衣類、雑貨などを扱う店がひしめき合っています。年末の買い出し風景は東京の冬の風物詩となっています。',
        place_photo_url: null as string | null,
        place_era_start: 1946 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 36,
        place_name: '銀座四丁目交差点',
        lat: 35.671079,
        lng: 139.764906,
        place_description: '銀座の中心地であり、和光の時計塔と銀座三越が対角に位置する交差点です。高級ブランド店や老舗百貨店が立ち並び、日本一地価が高い場所としても知られます。週末は歩行者天国となり、銀ブラを楽しむ人々で賑わいます。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 37,
        place_name: '代々木公園',
        lat: 35.671649,
        lng: 139.695304,
        place_description: '都心で一番広い空が見える森林公園です。かつては陸軍の練兵場や米軍宿舎（ワシントンハイツ）、東京五輪の選手村でした。週末には様々な国際フェスティバルやイベントが開催され、多くの人で賑わいます。',
        place_photo_url: null as string | null,
        place_era_start: 1967 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 38,
        place_name: '等々力渓谷',
        lat: 35.606367,
        lng: 139.645732,
        place_description: '東京23区内唯一の渓谷です。多摩川に注ぐ谷沢川沿いに遊歩道が整備されており、都会の喧騒を忘れるような静寂と自然が残っています。古墳や不動の滝などの史跡もあり、夏は涼を求める人々で賑わいます。',
        place_photo_url: null as string | null,
        place_era_start: null as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 39,
        place_name: 'サンシャイン60',
        lat: 35.729503,
        lng: 139.718058,
        place_description: '池袋にある超高層ビルです。かつて東洋一の高さを誇りました。最上階の展望台「てんぼうパーク」に加え、水族館、プラネタリウム、ナンジャタウンなどのアミューズメント施設が充実しており、一日中楽しめます。',
        place_photo_url: null as string | null,
        place_era_start: 1978 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 40,
        place_name: '秋葉原電気街',
        lat: 35.699667,
        lng: 139.771343,
        place_description: '世界有数の電気街であり、アニメ、マンガ、ゲームなどのサブカルチャーの聖地です。電子部品から最新家電、メイドカフェまで多種多様な店舗が集まり、独特の熱気を放っています。外国人観光客にも大変人気があります。',
        place_photo_url: null as string | null,
        place_era_start: 1945 as number | null, // 闇市からの発展
        place_era_end: null as number | null,
    },

    // 41-50: その他著名スポット・レトロ・近代
    {
        place_id: 41,
        place_name: '東京ドーム',
        lat: 35.705623,
        lng: 139.751919,
        place_description: '日本初の屋根付き球場です。読売ジャイアンツの本拠地であり、野球観戦だけでなく、大規模なコンサートやイベント会場としても使用されます。併設の「東京ドームシティ」には遊園地やスパ施設などがあります。',
        place_photo_url: null as string | null,
        place_era_start: 1988 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 42,
        place_name: '深大寺',
        lat: 35.666278,
        lng: 139.549219,
        place_description: '調布市にある、浅草寺に次いで都内で二番目に古い歴史を持つ古刹です。豊かな湧き水に恵まれ、周辺には名物の「深大寺そば」を食べさせる店が立ち並びます。隣接する神代植物公園とともに、自然と歴史を楽しめるスポットです。',
        place_photo_url: null as string | null,
        place_era_start: 733 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 43,
        place_name: '柴又帝釈天',
        lat: 35.758414,
        lng: 139.878342,
        place_description: '映画「男はつらいよ」の舞台として有名な葛飾区柴又にある寺院です。見事な木彫刻のギャラリーや庭園が見どころです。参道には草団子の店やレトロな建物が並び、下町の風情を色濃く残しています。',
        place_photo_url: null as string | null,
        place_era_start: 1629 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 44,
        place_name: '高尾山',
        lat: 35.625078,
        lng: 139.243685,
        place_description: '都心から電車で約1時間で行ける標高599mの山です。ミシュラン・グリーンガイドで三つ星を獲得しました。ケーブルカーやリフトもあり、初心者でも気軽に登山を楽しめるため、世界一登山客が多い山と言われています。',
        place_photo_url: null as string | null,
        place_era_start: 744 as number | null, // 薬王院開山
        place_era_end: null as number | null,
    },
    {
        place_id: 45,
        place_name: '谷中銀座商店街',
        lat: 35.727581,
        lng: 139.765662,
        place_description: '下町情緒が残る「谷根千」エリアを代表する商店街です。「夕やけだんだん」と呼ばれる階段からの夕景が有名で、惣菜店や猫グッズの店などが並びます。昭和レトロな雰囲気を求めて多くの人が散策に訪れます。',
        place_photo_url: null as string | null,
        place_era_start: 1945 as number | null, // 戦後自然発生的に形成
        place_era_end: null as number | null,
    },
    {
        place_id: 46,
        place_name: '豊洲市場',
        lat: 35.644463,
        lng: 139.785758,
        place_description: '2018年に築地から移転した公設卸売市場です。最新の衛生管理機能を備えた閉鎖型施設で、マグロの競りを見学デッキから見ることができます。新鮮な魚介類を楽しめる飲食店街や、屋上緑化広場も併設されています。',
        place_photo_url: null as string | null,
        place_era_start: 2018 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 47,
        place_name: '旧古河庭園',
        lat: 35.742468,
        lng: 139.746687,
        place_description: '大正初期の庭園の原型を留める国の名勝です。ジョサイア・コンドル設計の石造りの洋館と洋風庭園、そして小川治兵衛作庭の日本庭園が見事に調和しています。春と秋にはバラの名所として華やかに彩られます。',
        place_photo_url: null as string | null,
        place_era_start: 1919 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 48,
        place_name: '国立競技場',
        lat: 35.677918,
        lng: 139.714247,
        place_description: '2020年東京オリンピック・パラリンピックのメインスタジアムです。隈研吾氏らが設計し、「杜のスタジアム」をコンセプトに、木材を多用した和のテイストが特徴です。周辺の神宮外苑の緑と調和したデザインとなっています。',
        place_photo_url: null as string | null,
        place_era_start: 2019 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 49,
        place_name: '両国国技館',
        lat: 35.696956,
        lng: 139.793309,
        place_description: '大相撲の聖地であり、年3回の東京本場所が開催されます。すり鉢状の客席と吊り屋根が特徴的です。相撲博物館が併設されているほか、場所中以外でもイベント会場として使用されます。焼き鳥が名物です。',
        place_photo_url: null as string | null,
        place_era_start: 1985 as number | null,
        place_era_end: null as number | null,
    },
    {
        place_id: 50,
        place_name: 'レインボーブリッジ',
        lat: 35.636564,
        lng: 139.763143,
        place_description: '芝浦とお台場を結ぶ吊り橋で、東京港のシンボルです。遊歩道（レインボープロムナード）があり、歩いて渡ることも可能です。夜間は季節やイベントに合わせて美しくライトアップされ、東京湾の夜景を彩ります。',
        place_photo_url: null as string | null,
        place_era_start: 1993 as number | null,
        place_era_end: null as number | null,
    },
];